name: Update README

on:
  push:
    paths:
      - 'web/src/pages/blog/**'
      - 'web/src/pages/note/**'
      - 'web/public/humans.txt'
  workflow_dispatch:
  issues:
    types:
      - closed
      - deleted
      - edited

jobs:
  update-readme:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.ref}}
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - run: bun ./scripts/notes-from-issue.ts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create README
        run: bun ./scripts/generate-readme.js
      - name: Commit changes
        run: |
          git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --local user.name "${GITHUB_ACTOR}"
          git add ../README.md
          if git commit --dry-run > /dev/null; then
            git commit -m "chore: update README with latest posts"
            git push
          fi
