name: Update README

on:
  push:
    paths:
      - 'web/src/pages/blog/**'
      - 'web/src/pages/note/**'
      - 'web/public/humans.txt'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: bun install

      - name: Create README
        run: bun ./scripts/generate-readme.js

      - name: Commit changes
        run: |
          git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --local user.name "${GITHUB_ACTOR}"
          git add ../README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "chore: update README with latest posts"
          git push
